apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-api
  name: product-api
  namespace: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - image: yahiaalioua/product-api:product-api::main
        imagePullPolicy: IfNotPresent
        name: product-api
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
