apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-api
  name: product-api-loadbalancer
  namespace: product-api
spec:
  ports:
  - nodePort: 32747
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: product-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 143.198.249.129
