apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-08-04T17:39:54Z"
  generation: 1
  labels:
    app: product-api
  name: product-api
  namespace: product-api
  resourceVersion: "340377"
  uid: 731cc146-cfc0-4fcc-9453-5a0764978395
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: product-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-api
    spec:
      containers:
      - image: yahiaalioua/product-api:1.0.0
        imagePullPolicy: IfNotPresent
        name: product-api
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-08-04T17:40:04Z"
    lastUpdateTime: "2023-08-04T17:40:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-08-04T17:39:54Z"
    lastUpdateTime: "2023-08-04T17:40:04Z"
    message: ReplicaSet "product-api-7965d48bdc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
