apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: ad1ed4e2-9ebf-4031-a238-b39143debb72
  creationTimestamp: "2023-08-04T20:52:41Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: product-api
  name: product-api-loadbalancer
  namespace: product-api
  resourceVersion: "379604"
  uid: 8a5626aa-ee46-4fcb-9964-e18a006eb49a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.245.241.173
  clusterIPs:
  - 10.245.241.173
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32747
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: product-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 143.198.249.129
