name: product-api-docker-build-push

on:
  push:
    branches:
      - 'main'
    
env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
  
  deploy_to_kubernetes:
    runs-on: "self-hosted"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2            
      
      - name: Deploy nginx
        uses: actions-hub/kubectl@master
        with:
          args: run nginx --image=nginx --namespace=product-api
  
