name: product-api-docker-build-push

on:
  push:
    branches:
      - 'main'
    paths-ignore:
     # - '**/*.yaml'
      - '**/*.yml'
      - '**/*.txt'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    
env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
        
          
      
  
  deploy_to_kubernetes:
    runs-on: "self-hosted"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
        
      - name: Fetch Image Tags
        id: fetch_tags
        run: |
          TOKEN=${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME=yahiaalioua/product-api  # Replace with your Docker image name
          API_URL="https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/?ordering=last_updated"
          TAGS_JSON=$(curl -s -H "Authorization: Bearer $TOKEN" $API_URL)
          echo "::set-output name=tags::$(echo $TAGS_JSON | jq -r '.results[].name')"

      - name: Get Latest Image Tag
        id: get_latest_tag
        run: |
          TAGS=${{ steps.fetch_tags.outputs.tags }}
          LATEST_TAG=$(echo "$TAGS" | sort -V | tail -1)
          echo "::set-output name=latest_tag::$LATEST_TAG"
        
      - name: Update Kubernetes Deployment Image
        run: |
          FULL_IMAGE_TAG=${{ steps.metadata.outputs.tags }}
          sed -i "s|image: yahiaalioua/product-api:.*|$LATEST_TAG|g" k8s_Deployment/product-api-deployment.yaml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s_Deployment/product-api-deployment.yaml
          git commit -m "Update deployment YAML with Docker image tag"
          git push origin main

      - name: Deploy api(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k8s_Deployment/product-api-deployment.yaml
      
      - name: Deploy load balancer service(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k8s_Deployment/product-api-loadbalancer.yaml
  
