name: product-api-docker-build-push

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.txt'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    
env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
  
  
  deploy_to_kubernetes:
    runs-on: "self-hosted"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Update Kubernetes Deployment Image
        run: |
          GENERATED_TAG=${{ needs.build_and_push_docker_image.outputs.GENERATED_TAG }}
          sed -i "s/<IMAGE_TAG>/$GENERATED_TAG/g" k8s_Deployment/product-api-deployment.yaml

      - name: Deploy api(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f https://raw.githubusercontent.com/yahiaalioua/Api_MySql_DB_Kubernetes_Deployment/main/k8s_Deployment/product-api-deployment.yaml
      
      - name: Deploy load balancer service(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f https://raw.githubusercontent.com/yahiaalioua/Api_MySql_DB_Kubernetes_Deployment/main/k8s_Deployment/product-api-loadbalancer.yaml
  
