name: product-api-docker-build-push

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.txt'
    
env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
  build_and_push_docker_image:
    runs-on: "self-hosted"
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: yahiaalioua/product-api:latest
  
  deploy_to_kubernetes:
    needs: build_and_push_docker_image
    runs-on: "self-hosted"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2      

      - name: Deploy api(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f https://raw.githubusercontent.com/yahiaalioua/Api_MySql_DB_Kubernetes_Deployment/main/k8s_Deployment/product-api-deployment.yaml
      
      - name: Deploy load balancer service(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f https://raw.githubusercontent.com/yahiaalioua/Api_MySql_DB_Kubernetes_Deployment/main/k8s_Deployment/product-api-loadbalancer.yaml
  
