name: product-api-docker-build-push

on:
  push:
    branches:
      - 'main'
    paths-ignore:
     # - '**/*.yaml'
      - '**/*.yml'
      - '**/*.txt'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    
env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
        
          
      
  
  deploy_to_kubernetes:
    runs-on: "self-hosted"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
        
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: yahiaalioua/product-api:${{ steps.metadata.outputs.tags }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
        
      - name: Update Kubernetes Deployment Image
        run: |
          FULL_IMAGE_TAG=${{ steps.metadata.outputs.tags }}
          sed -i "s|image: yahiaalioua/product-api:.*|yahiaalioua/product-api:$FULL_IMAGE_TAG|g" k8s_Deployment/product-api-deployment.yaml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s_Deployment/product-api-deployment.yaml
          git commit -m "Update deployment YAML with Docker image tag"
          git push origin main

      - name: Deploy api(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k8s_Deployment/product-api-deployment.yaml
      
      - name: Deploy load balancer service(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k8s_Deployment/product-api-loadbalancer.yaml
  
